apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
  - name: node-port
    port: 30001
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: ClusterIP
